In [ ]:
! pip install -q kaggle

In [ ]:
from google.colab import files

files.upload()

Saving kaggle.json to kaggle (1).json

{'kaggle.json': b'{"username":"abanoubmaher","key":"9cff2f3afe257c6c089eec65a12153a0"}'}

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
! cp kaggle.json ~/.kaggle/

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle datasets list

ref                                                                       title                                                size  lastUpdated          downloadCount  voteCount  usabilityRating
------------------------------------------------------------------------  --------------------------------------------------  -----  -------------------  -------------  ---------  ---------------
datasets/piterfm/2022-ukraine-russian-war                                 2022 Ukraine Russia War                               1KB  2022-03-24 09:08:51           2583        181  1.0
datasets/prasertk/healthy-lifestyle-cities-report-2021                    Healthy Lifestyle Cities Report 2021                  2KB  2022-03-03 00:26:02           2849         94  1.0
datasets/prasertk/netflix-daily-top-10-in-us                              Netflix daily top 10                                 70KB  2022-03-12 13:22:19           1267         35  1.0
datasets/vivek468/superstore-dataset-final                                Superstore Dataset                                  550KB  2022-02-17 11:33:07           4006         96  1.0
datasets/equinxx/spotify-top-50-songs-in-2021                             Spotify top 50 songs in 2021                          4KB  2022-03-17 22:59:45           1367         40  1.0
datasets/kamilpytlak/personal-key-indicators-of-heart-disease             Personal Key Indicators of Heart Disease              3MB  2022-02-16 10:18:03           4171         77  1.0
datasets/majyhain/height-of-male-and-female-by-country-2022               Height of Male and Female by Country 2022             4KB  2022-02-02 00:40:19           7126        191  1.0
datasets/pranalibose/amazon-seller-order-status-prediction                Amazon Seller - Order Status Prediction              23KB  2022-02-26 06:31:07           2139         58  0.88235295
datasets/ashishjangra27/ted-talks                                         TED Talks                                           298KB  2022-02-23 15:16:08           2490        112  1.0
datasets/shivkumarganesh/road-traffic-deaths-1990-to-2019                 Road traffic deaths, 1990 to 2019                    74KB  2022-03-24 07:52:55            680         32  1.0
datasets/ramjasmaurya/exports-and-imports-of-india19972022                Exports and Imports of India(1997-2022)              89KB  2022-03-08 14:30:40           1026         27  1.0
datasets/shivkumarganesh/tinder-google-play-store-review                  Tinder Dating App - Google Play Store Review         79MB  2022-03-19 10:32:39            352         32  1.0
datasets/maricinnamon/walt-disney-character-dataset                       Walt Disney Character Dataset                        35KB  2022-03-15 12:51:01            533         29  1.0
datasets/timmofeyy/-cerial-prices-changes-within-last-30-years            🌽 Cerial Prices Changes Within Last 30 Years          8KB  2022-03-17 11:46:22            395         16  1.0
datasets/timmofeyy/-coffee-rice-and-beef-price-changes-for-30-years       ☕Coffee, Rice and Beef Prices Changes for 30 Years    5KB  2022-03-15 10:41:06            593         30  1.0
datasets/minisam/marvel-movie-dataset                                     Marvel Movie dataset                                  9KB  2022-03-02 20:03:37           1498         28  0.9411765
datasets/soumyadiptadas/students-math-score-for-different-teaching-style  Student's math score for different teaching style     2KB  2022-02-23 12:36:06           2773         54  1.0
datasets/danielfesalbon/covid-19-global-reports-early-march-2022          COVID -19 Global Reports early March 2022             2MB  2022-03-05 10:51:39           1103         29  1.0
datasets/meetnagadia/walmart-stock-price-from-19722022                    Walmart Stock Price from 1972-2022                  221KB  2022-03-08 11:13:54            568         28  1.0
datasets/vinitshah0110/food-composition                                   Food Composition                                    159KB  2022-03-14 05:04:39            801         39  1.0

In [ ]:
!kaggle datasets download -d tawsifurrahman/covid19-radiography-database

Downloading covid19-radiography-database.zip to /content
100% 778M/778M [00:04<00:00, 223MB/s]
100% 778M/778M [00:04<00:00, 187MB/s]

In [ ]:
! cp covid19-radiography-database.zip /content/gdrive/MyDrive/GP/ML/

In [ ]:
%cd gdrive/MyDrive/ML/

/content/gdrive/.shortcut-targets-by-id/18dU1rLgpQvebEJhVNBguM_6BKp5uFSH7/ML

In [ ]:
!ls

Covid-19_Detection.ipynb	  Covid.csv	 train_data.csv
covid19-radiography-database.zip  Normal.csv	 ViralPneumonia.csv
COVID-19_Radiography_Dataset	  test_data.csv

In [ ]:
! unzip covid19-radiography-database.zip

Streaming output truncated to the last 5000 lines.
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7921.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7922.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7923.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7924.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7925.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7926.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7927.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7928.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7929.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-793.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7930.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7931.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7932.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7933.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7934.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7935.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7936.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7937.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7938.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7939.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-794.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7940.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7941.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7942.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7943.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7944.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7945.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7946.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7947.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7948.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7949.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-795.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7950.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7951.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7952.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7953.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7954.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7955.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7956.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7957.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7958.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7959.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-796.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7960.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7961.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7962.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7963.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7964.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7965.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7966.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7967.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7968.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7969.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-797.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7970.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7971.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7972.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7973.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7974.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7975.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7976.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7977.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7978.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7979.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-798.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7980.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7981.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7982.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7983.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7984.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7985.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7986.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7987.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7988.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7989.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-799.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7990.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7991.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7992.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7993.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7994.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7995.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7996.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7997.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7998.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-7999.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-80.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-800.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8000.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8001.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8002.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8003.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8004.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8005.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8006.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8007.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8008.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8009.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-801.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8010.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8011.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8012.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8013.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8014.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8015.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8016.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8017.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8018.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8019.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-802.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8020.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8021.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8022.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8023.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8024.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8025.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8026.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8027.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8028.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8029.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-803.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8030.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8031.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8032.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8033.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8034.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8035.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8036.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8037.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8038.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8039.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-804.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8040.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8041.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8042.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8043.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8044.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8045.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8046.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8047.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8048.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8049.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-805.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8050.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8051.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8052.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8053.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8054.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8055.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8056.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8057.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8058.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8059.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-806.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8060.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8061.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8062.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8063.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8064.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8065.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8066.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8067.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8068.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8069.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-807.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8070.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8071.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8072.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8073.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8074.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8075.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8076.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8077.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8078.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8079.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-808.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8080.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8081.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8082.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8083.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8084.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8085.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8086.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8087.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8088.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8089.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-809.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8090.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8091.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8092.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8093.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8094.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8095.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8096.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8097.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8098.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8099.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-81.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-810.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8100.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8101.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8102.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8103.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8104.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8105.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8106.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8107.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8108.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8109.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-811.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8110.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8111.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8112.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8113.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8114.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8115.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8116.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8117.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8118.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8119.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-812.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8120.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8121.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8122.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8123.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8124.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8125.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8126.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8127.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8128.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8129.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-813.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8130.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8131.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8132.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8133.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8134.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8135.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8136.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8137.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8138.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8139.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-814.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8140.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8141.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8142.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8143.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8144.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8145.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8146.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8147.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8148.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8149.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-815.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8150.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8151.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8152.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8153.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8154.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8155.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8156.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8157.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8158.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8159.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-816.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8160.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8161.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8162.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8163.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8164.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8165.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8166.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8167.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8168.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8169.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-817.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8170.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8171.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8172.png
  inflating: COVID-19_Radiography_Dataset/Normal/masks/Normal-8173.png

In [ ]:
!ls

gdrive	sample_data

In [ ]:
cd COVID-19_Radiography_Dataset/

/content/gdrive/MyDrive/GP/ML/COVID-19_Radiography_Dataset

In [ ]:
!ls

 COVID			      Normal.metadata.xlsx
 COVID.metadata.xlsx	      README.md.txt
 Lung_Opacity		     'Viral Pneumonia'
 Lung_Opacity.metadata.xlsx  'Viral Pneumonia.metadata.xlsx'
 Normal

In [ ]:
%cd ..

/content/gdrive/MyDrive/GP/ML

In [ ]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
!pip install openpyxl

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: openpyxl in /usr/local/lib/python3.7/dist-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl) (1.1.0)

In [ ]:
train_cov=pd.read_excel("./COVID-19_Radiography_Dataset/COVID.metadata.xlsx")
train_cov["label"]= "COVID"
train_nor=pd.read_excel("./COVID-19_Radiography_Dataset/Normal.metadata.xlsx").sample(4192)
train_nor["label"]= "NORMAL"
train_pneu=pd.read_excel("./COVID-19_Radiography_Dataset/Viral Pneumonia.metadata.xlsx")
train_pneu["label"]= "PNEUMONIA"

FileNotFoundError: ignored

In [ ]:
train_nor.head()

,FILE NAME,FORMAT,SIZE,URL,label
9671,NORMAL-9672,PNG,256*256,https://www.kaggle.com/paultimothymooney/chest...,NORMAL
7057,NORMAL-7058,PNG,256*256,https://www.kaggle.com/c/rsna-pneumonia-detect...,NORMAL
4239,NORMAL-4240,PNG,256*256,https://www.kaggle.com/c/rsna-pneumonia-detect...,NORMAL
7229,NORMAL-7230,PNG,256*256,https://www.kaggle.com/c/rsna-pneumonia-detect...,NORMAL
8153,NORMAL-8154,PNG,256*256,https://www.kaggle.com/c/rsna-pneumonia-detect...,NORMAL

In [ ]:
train_cov.head()

,FILE NAME,FORMAT,SIZE,URL,label
0,COVID-1,PNG,256*256,https://sirm.org/category/senza-categoria/covi...,COVID
1,COVID-2,PNG,256*256,https://sirm.org/category/senza-categoria/covi...,COVID
2,COVID-3,PNG,256*256,https://sirm.org/category/senza-categoria/covi...,COVID
3,COVID-4,PNG,256*256,https://sirm.org/category/senza-categoria/covi...,COVID
4,COVID-5,PNG,256*256,https://sirm.org/category/senza-categoria/covi...,COVID

In [ ]:
train_pneu.head()

,FILE NAME,FORMAT,SIZE,URL,label
0,Viral Pneumonia-1,PNG,256*256,https://www.kaggle.com/paultimothymooney/chest...,PNEUMONIA
1,Viral Pneumonia-2,PNG,256*256,https://www.kaggle.com/paultimothymooney/chest...,PNEUMONIA
2,Viral Pneumonia-3,PNG,256*256,https://www.kaggle.com/paultimothymooney/chest...,PNEUMONIA
3,Viral Pneumonia-4,PNG,256*256,https://www.kaggle.com/paultimothymooney/chest...,PNEUMONIA
4,Viral Pneumonia-5,PNG,256*256,https://www.kaggle.com/paultimothymooney/chest...,PNEUMONIA

In [ ]:
import os
import pandas as pd
y = 0
# os.walk --> return folders and files name
# './COVID-19_Radiography_Dataset/COVID'
dataCovid = []
for dirname, _, filenames in os.walk('./COVID-19_Radiography_Dataset/COVID'):
    for filename in filenames:
          dataCovid.append(os.path.join(dirname, filename))

dataViralPneumonia = []
for dirname, _, filenames in os.walk('./COVID-19_Radiography_Dataset/Viral Pneumonia'):
    for filename in filenames:
          dataViralPneumonia.append(os.path.join(dirname, filename))

dataNormal = []
for dirname, _, filenames in os.walk('./COVID-19_Radiography_Dataset/Normal'):
    for filename in filenames:
          dataNormal.append(os.path.join(dirname, filename))

In [ ]:
dataNormal

['./COVID-19_Radiography_Dataset/Normal/images/Normal-4108.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-10108.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-6885.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9894.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-7889.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3974.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-7642.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9547.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-7233.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3553.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3158.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-1674.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-755.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-6719.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-2615.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-2668.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8475.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-456.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-4375.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9356.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9849.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-4379.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3090.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-664.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-5780.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3491.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-4560.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-7688.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9206.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-4117.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-1661.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8676.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3625.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-6411.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-557.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-2714.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8446.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8054.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-621.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9164.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-2295.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-6509.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-1786.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8852.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-2169.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-6383.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-7584.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3796.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-10185.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-1057.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-6393.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8974.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-477.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8073.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-1109.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-7812.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3101.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9362.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9342.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-748.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-6734.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-2122.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-2887.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-945.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-805.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-4791.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-5956.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8178.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8945.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-7279.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-5997.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-5721.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-4197.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3145.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3875.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-6759.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-5917.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-1776.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9741.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3432.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-4233.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-6332.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3141.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-1044.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-1869.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-2519.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-4627.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3549.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3243.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3304.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9243.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-2948.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8944.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3401.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-1603.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3991.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-802.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-1177.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8422.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-6067.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8325.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3079.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-2022.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-4619.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3454.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-2204.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-5010.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-1358.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9484.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3627.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-6429.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-2712.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-4349.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-4879.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-5866.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-4484.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-1656.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-3764.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-5759.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-6079.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8808.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8626.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8706.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-87.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-883.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8299.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8240.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8580.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8220.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8832.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8535.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8856.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8473.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8214.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8394.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8381.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8478.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8427.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8699.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8607.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8862.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8383.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8668.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8257.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8274.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8277.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8651.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-882.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8620.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8644.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8767.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8259.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8660.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8740.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8635.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8499.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8618.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8239.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8269.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8517.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8725.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8551.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8420.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8819.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8711.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8369.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8851.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8306.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8778.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8557.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-862.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8484.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8270.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8198.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8802.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8542.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8187.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8513.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8174.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8560.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8705.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8498.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8495.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8315.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8686.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8629.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8165.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8177.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8780.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8319.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-826.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8431.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-943.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9037.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9273.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9474.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9372.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9533.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9439.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9343.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-92.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9526.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9359.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9385.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9067.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9063.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8887.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9311.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9263.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8992.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9153.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9508.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9188.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9583.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9472.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9191.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9163.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9453.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-915.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9076.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8886.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9327.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8869.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9339.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9083.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9322.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9160.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9528.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9421.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9279.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9216.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9078.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9237.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9074.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9173.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9056.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9352.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9147.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9504.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-887.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8881.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-889.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-930.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9405.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-947.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-920.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-933.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9047.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-942.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8950.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9407.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9280.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9514.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9527.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8920.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9166.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9093.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9118.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8985.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9077.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9064.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9137.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8955.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9334.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9203.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9130.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8915.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9042.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9324.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9155.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9000.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8976.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9476.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9369.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-888.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9219.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8951.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9116.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9110.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8884.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9087.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9101.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9423.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9390.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9125.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9408.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9267.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8901.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9012.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9033.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9400.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9084.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9325.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9584.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9075.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8952.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8924.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9323.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9023.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9202.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9375.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-8892.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9512.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9208.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9181.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9888.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-971.png',
 './COVID-19_Radiography_Dataset/Normal/images/Normal-9714.png',

In [ ]:
len(dataNormal)

3018

In [ ]:
len(dataCovid)

7028

In [ ]:
len(dataViralPneumonia)

2653

In [ ]:
df_covid = pd.DataFrame(dataCovid)
df_viralPneumonia = pd.DataFrame(dataViralPneumonia)
df_normal = pd.DataFrame(dataNormal)

In [ ]:
df_covid.head()

                                                   0
0  ./COVID-19_Radiography_Dataset/COVID/masks/COV...
1  ./COVID-19_Radiography_Dataset/COVID/masks/COV...
2  ./COVID-19_Radiography_Dataset/COVID/masks/COV...
3  ./COVID-19_Radiography_Dataset/COVID/masks/COV...
4  ./COVID-19_Radiography_Dataset/COVID/masks/COV...

In [ ]:
df_covid.rename(columns = {0:'images'}, inplace = True)
df_covid["target"] = "COVID-19"

df_viralPneumonia.rename(columns = {0:'images'}, inplace = True)
df_viralPneumonia["target"] = "ViralPneumonia"

df_normal.rename(columns = {0:'images'}, inplace = True)
df_normal["target"] = "Normal"

In [ ]:
df_covid.head()

                                              images    target
0  ./COVID-19_Radiography_Dataset/COVID/masks/COV...  COVID-19
1  ./COVID-19_Radiography_Dataset/COVID/masks/COV...  COVID-19
2  ./COVID-19_Radiography_Dataset/COVID/masks/COV...  COVID-19
3  ./COVID-19_Radiography_Dataset/COVID/masks/COV...  COVID-19
4  ./COVID-19_Radiography_Dataset/COVID/masks/COV...  COVID-19

In [ ]:
df_normal.head()

                                              images  target
0  ./COVID-19_Radiography_Dataset/Normal/images/N...  Normal
1  ./COVID-19_Radiography_Dataset/Normal/images/N...  Normal
2  ./COVID-19_Radiography_Dataset/Normal/images/N...  Normal
3  ./COVID-19_Radiography_Dataset/Normal/images/N...  Normal
4  ./COVID-19_Radiography_Dataset/Normal/images/N...  Normal

In [ ]:
df_viralPneumonia.head()

                                              images          target
0  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia
1  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia
2  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia
3  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia
4  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia

In [ ]:
#saving (df)paths in csv files
df_covid.to_csv('Covid.csv')
df_normal.to_csv('Normal.csv')
df_viralPneumonia.to_csv('ViralPneumonia.csv')

In [ ]:
!ls

Covid-19_Detection.ipynb	  Covid.csv	 train_data.csv
covid19-radiography-database.zip  Normal.csv	 ViralPneumonia.csv
COVID-19_Radiography_Dataset	  test_data.csv

In [ ]:
import math

test_data_idx = math.ceil(df_covid.shape[0]/4)
train_covid = df_covid.iloc[test_data_idx:]
test_covid = df_covid.iloc[:test_data_idx-1]

In [ ]:
test_normal_data_idx = math.ceil(df_normal.shape[0]/4)
train_normal = df_normal.iloc[test_normal_data_idx:]
test_normal = df_normal.iloc[:test_normal_data_idx-1]

In [ ]:
test_viralPneumonia_data_idx = math.ceil(df_viralPneumonia.shape[0]/4)
train_viralPneumonia = df_viralPneumonia.iloc[test_viralPneumonia_data_idx:]
test_viralPneumonia = df_viralPneumonia.iloc[:test_viralPneumonia_data_idx-1]

In [ ]:
train_data = pd.concat([train_covid,train_normal, train_viralPneumonia])
test_data = pd.concat([test_covid,test_normal,test_viralPneumonia])

In [ ]:
train_data.reset_index()

      index                                             images          target
0      1757  ./COVID-19_Radiography_Dataset/COVID/masks/COV...        COVID-19
1      1758  ./COVID-19_Radiography_Dataset/COVID/masks/COV...        COVID-19
2      1759  ./COVID-19_Radiography_Dataset/COVID/masks/COV...        COVID-19
3      1760  ./COVID-19_Radiography_Dataset/COVID/masks/COV...        COVID-19
4      1761  ./COVID-19_Radiography_Dataset/COVID/masks/COV...        COVID-19
...     ...                                                ...             ...
9518   2648  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia
9519   2649  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia
9520   2650  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia
9521   2651  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia
9522   2652  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia

[9523 rows x 3 columns]

In [ ]:
test_data.reset_index()

      index                                             images          target
0         0  ./COVID-19_Radiography_Dataset/COVID/masks/COV...        COVID-19
1         1  ./COVID-19_Radiography_Dataset/COVID/masks/COV...        COVID-19
2         2  ./COVID-19_Radiography_Dataset/COVID/masks/COV...        COVID-19
3         3  ./COVID-19_Radiography_Dataset/COVID/masks/COV...        COVID-19
4         4  ./COVID-19_Radiography_Dataset/COVID/masks/COV...        COVID-19
...     ...                                                ...             ...
3168    658  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia
3169    659  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia
3170    660  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia
3171    661  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia
3172    662  ./COVID-19_Radiography_Dataset/Viral Pneumonia...  ViralPneumonia

[3173 rows x 3 columns]

In [ ]:
train_data.to_csv('train_data.csv')
test_data.to_csv('test_data.csv')

In [ ]:
train_data=pd.read_csv('train_data.csv')
test_data=pd.read_csv('test_data.csv')

In [ ]:
#data augmantation
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale=1./255,rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,horizontal_flip=True)

# Convert images to grayscale

val_datagen=ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_dataframe(
    train_data,
    x_col='images',
    y_col='target',
    target_size=(256, 256),
    color_mode="grayscale",
    batch_size=32,
    shuffle=True,
    class_mode='sparse',
    validate_filenames=True)

validation_generator = val_datagen.flow_from_dataframe(
    test_data,
    x_col='images',
    y_col='target',
    target_size=(256, 256),
    shuffle=False,
    batch_size=32,
    color_mode="grayscale",
    class_mode='sparse',
    validate_filenames=True)

Found 9523 validated image filenames belonging to 3 classes.
Found 3173 validated image filenames belonging to 3 classes.

In [ ]:

from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout
from tensorflow.keras import layers
from tensorflow.keras.metrics import AUC
from tensorflow.keras.activations import sigmoid
from tensorflow.keras.optimizers import SGD, Adam, Adamax
from tensorflow.keras import Model
import tensorflow as tf

In [ ]:
model = tf.keras.models.Sequential([
      layers.Conv2D(64, 3, activation='relu', input_shape=(256, 256,1)),
      layers.MaxPooling2D(),
      layers.Dropout(0.3),
      layers.Conv2D(128,3,activation='relu'),
      layers.MaxPooling2D(),
      layers.Conv2D(256, 3, activation='relu'),
      layers.MaxPooling2D(),
      layers.Dropout(0.3),
      layers.Conv2D(512, 3, activation='relu'),
      layers.MaxPooling2D(),
      layers.Dropout(0.2),
      layers.Flatten(),
      layers.Dense(1024, activation='relu'),
      layers.Dropout(0.15),
      layers.Dense(3, activation= 'softmax')
    ])

In [ ]:
import tensorflow.keras
from tensorflow.keras.metrics import AUC
opt = tensorflow.keras.optimizers.Adam(learning_rate = 1e-3)
model.compile(optimizer=opt,loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
nb_epochs = 50
batch_size=32

In [ ]:
hist= model.fit(
    train_generator,
    epochs=nb_epochs,
    validation_data=validation_generator)

Epoch 1/10
222/222 [==============================] - 3434s 15s/step - loss: 1.1886 - accuracy: 0.5215 - val_loss: 1.0228 - val_accuracy: 0.4727
Epoch 2/10
222/222 [==============================] - 3051s 14s/step - loss: 0.7962 - accuracy: 0.6323 - val_loss: 0.7860 - val_accuracy: 0.6885
Epoch 3/10
222/222 [==============================] - 3042s 14s/step - loss: 0.7144 - accuracy: 0.6678 - val_loss: 0.6348 - val_accuracy: 0.7220
Epoch 4/10
104/222 [=============>................] - ETA: 24:42 - loss: 0.6738 - accuracy: 0.6888

In [ ]:
model.save('model.h5')

In [ ]:
model.save_weights("model.hdf5")

In [ ]:
TFlite_Model = tf.keras.models.load_model('model.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("TFlite_Model.tflite", "wb").write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmpfve6mol9/assets

WARNING:absl:Buffer deduplication procedure will be skipped when flatbuffer library is not properly loaded

417261680